### Image analysis

Before we talk about image analysis, and libraries such as OpenCV, we must talk about a library called NumPy.

#### What is NumPy?

Essentially, it is a library that allows you to (efficiently) manage and manipulate multi-dimensional arrays. 

If you've taken matrix theory, or are familiar with matrices, you many helpful standard functions. Lets consider the following multidimensional array:

In [11]:
import numpy
import random

my_list = [random.randint(0, 100) for _ in range(20)]
print(my_list)

nd_list = numpy.array(my_list)
nd_list = numpy.reshape(nd_list, (4, 5))
display(nd_list)

[100, 68, 68, 95, 17, 96, 63, 57, 22, 56, 91, 37, 21, 66, 6, 11, 83, 59, 35, 12]


array([[100,  68,  68,  95,  17],
       [ 96,  63,  57,  22,  56],
       [ 91,  37,  21,  66,   6],
       [ 11,  83,  59,  35,  12]])

In [12]:
nd_list = nd_list.transpose()
display(nd_list)

array([[100,  96,  91,  11],
       [ 68,  63,  37,  83],
       [ 68,  57,  21,  59],
       [ 95,  22,  66,  35],
       [ 17,  56,   6,  12]])

In [13]:
nd_list = nd_list * [4, 8, 12, 16]
display(nd_list)

array([[ 400,  768, 1092,  176],
       [ 272,  504,  444, 1328],
       [ 272,  456,  252,  944],
       [ 380,  176,  792,  560],
       [  68,  448,   72,  192]])

In [14]:
nd_list = nd_list.dot([4, 8, 12, 16])
print(nd_list)

[23664 31696 22864 21392  7792]


You may be wondering why NumPy is important. Well, as many of you know, an image is multi-dimensional (as in, not 1D). For a single image, what do you think the dimension of the array would be?

#### OpenCV

Now, we can get started with OpenCV. There's some cool things you can do with OpenCV, such as contouring:

In [ ]:
#insert image here